# Generated by Django 4.2.16 on 2024-10-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.TextField(max_length=50)),
                ('dept_desc', models.TextField(max_length=200)),
            ],
        ),
    ]
